### ISSUE TITLE
Can't install on my raspberry

### ISSUE THREAD

**Issue by zecole123** [fjw/node-simplespi#3]
Hello,

when i try to install i get this error:
root@raspberrypi:~# npm install simplespi
npm http GET http://registry.npmjs.org/simplespi
npm http 304 http://registry.npmjs.org/simplespi

> simplespi@0.0.1 install /root/node_modules/simplespi
> node-gyp rebuild

make: Entering directory '/root/node_modules/simplespi/build'
  CXX(target) Release/obj.target/simplespi/simplespi.o
../simplespi.cc:14:0: warning: "ARRAY_SIZE" redefined [enabled by default]
/root/.node-gyp/0.6.19/src/node.h:86:0: note: this is the location of the previous definition
../simplespi.cc: In function âv8::Handlev8::Value Send(const v8::Arguments&)â:
../simplespi.cc:75:20: error: âO_RDWRâ was not declared in this scope
../simplespi.cc:75:26: error: âopenâ was not declared in this scope
simplespi.target.mk:76: recipe for target 'Release/obj.target/simplespi/simplespi.o' failed
make: **\* [Release/obj.target/simplespi/simplespi.o] Error 1
make: Leaving directory '/root/node_modules/simplespi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:70:17)
gyp ERR! stack     at maybeExit (child_process.js:362:16)
gyp ERR! stack     at Process.onexit (child_process.js:398:5)
gyp ERR! System Linux 3.12.28+
gyp ERR! command "node" "/root/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /root/node_modules/simplespi
gyp ERR! node -v v0.6.19
gyp ERR! node-gyp -v v0.9.6
gyp ERR! not ok
npm ERR! error installing simplespi@0.0.1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
npm WARN /usr/share/doc/nodejs/README.Debian
npm WARN

npm ERR! simplespi@0.0.1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the simplespi@0.0.1 install script.
npm ERR! This is most likely a problem with the simplespi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls simplespi
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 3.12.28+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "simplespi"
npm ERR! cwd /root
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message simplespi@0.0.1 install: `node-gyp rebuild`
npm ERR! message `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! errno {}
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm not ok

**Comment by jnovack** [comment]
Your node version is WAY out of date.

**Comment by ghost** [comment]
same issue with nodejs v 4.0.0

**Comment by jacebenson** [comment]
I'm getting the same issue with 4.0, 8.11.4, and 10.15.1
