### ISSUE TITLE
node v4.2.3

### ISSUE THREAD

**Issue by jnovack** [fjw/node-simplespi#4]
A number of errors occur while rebuilding under v4.2.3 due to the 
differences between `node_version.h` and `nan.h`

```
> simplespi@0.0.1 install /home/pi/rpiled/node_modules/leddriver/node_modules/simplespi
> node-gyp rebuild

make: Entering directory `/home/pi/rpiled/node_modules/leddriver/node_modules/simplespi/build'
  CXX(target) Release/obj.target/simplespi/simplespi.o
In file included from /home/pi/rpiled/node_modules/leddriver/node_modules/simplespi/.node-gyp/4.2.3/include/node/node.h:42:0,
                 from ../simplespi.cc:1:
/home/pi/rpiled/node_modules/leddriver/node_modules/simplespi/.node-gyp/4.2.3/include/node/v8.h:336:1: error: expected unqualified-id before 'using'
/home/pi/rpiled/node_modules/leddriver/node_modules/simplespi/.node-gyp/4.2.3/include/node/v8.h:469:1: error: expected unqualified-id before 'using'
/home/pi/rpiled/node_modules/leddriver/node_modules/simplespi/.node-gyp/4.2.3/include/node/v8.h:852:1: error: expected unqualified-id before 'using'
../simplespi.cc: In function 'void errormsg(const char*)':
../simplespi.cc:18:34: error: 'New' is not a member of 'v8::String'
../simplespi.cc:18:49: error: 'ThrowException' was not declared in this scope
../simplespi.cc: At global scope:
../simplespi.cc:32:1: error: 'Handle' does not name a type
../simplespi.cc:148:11: error: variable or field 'init' declared void
../simplespi.cc:148:11: error: 'Handle' was not declared in this scope
../simplespi.cc:148:24: error: expected primary-expression before '>' token
../simplespi.cc:148:26: error: 'exports' was not declared in this scope
../simplespi.cc:155:1: error: 'init' was not declared in this scope
../simplespi.cc:16:13: warning: 'void errormsg(const char*)' defined but not used [-Wunused-function]
../simplespi.cc:25:16: warning: 'mode' defined but not used [-Wunused-variable]
../simplespi.cc:26:16: warning: 'bits' defined but not used [-Wunused-variable]
../simplespi.cc:27:17: warning: 'speed' defined but not used [-Wunused-variable]
../simplespi.cc:28:17: warning: 'delay' defined but not used [-Wunused-variable]
make: *** [Release/obj.target/simplespi/simplespi.o] Error 1
make: Leaving directory `/home/pi/rpiled/node_modules/leddriver/node_modules/simplespi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node-v4.2.3-linux-armv6l/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.21+
gyp ERR! command "/opt/node-v4.2.3-linux-armv6l/bin/node" "/opt/node-v4.2.3-linux-armv6l/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/rpiled/node_modules/leddriver/node_modules/simplespi
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

Most of the errors are found fixed here: https://github.com/dberesford/exiv2node/pull/32/files

If I could hack my way into C, I'll try, but it's one of the few languages I do not know. :/

**Comment by jnovack** [comment]
Closed due to lack of interest.
